### ISSUE TITLE
Runtime error under Yosemite

### ISSUE THREAD

**Issue by jgclark** [ali-rantakari/icalBuddy#9] opened 2014-11-27 18:03 UTC
Using current version (1.8.8) I've been getting the following errors under Yosemite:

2014-11-27 18:01:12.846 icalBuddy[30650:3816422] Error loading /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation:  dlopen(/System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation, 265): no suitable image found.  Did find:
    /System/Library/PrivateFrameworks/CalendarFoundation.framework/CalendarFoundation: mach-o, but wrong architecture

It then goes on to produce the right information.

**Comment by edasque** [comment] 2014-12-01 16:47
I had the same issue. https://github.com/ali-rantakari/icalBuddy/issues/6 solved it

rm /usr/local/bin/icalBuddy
rm /usr/local/share/man/man1/icalBuddy*
brew install ical-buddy

**Comment by ali-rantakari** [comment] 2014-12-04 12:35
Yep, duplicate of #6

**Closed as completed by ali-rantakari** 2014-12-04 12:35 UTC
